version: "3"
services:
    app:
        image: python:3.12.1-alpine3.19
        tty: true
        working_dir: /app
        environment:
            - DEBUG=True
            - SESSION_SECRET=${APP_SECRET}
            - DB_HOST=db
            - DB_PORT=${DB_PORT}
            - DB_NAME=${DB_NAME}
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
        volumes:
            - ./:/app:z
        ports:
            - ${APP_EXPOSED}:8000
    db:
        image: postgres:16.1-alpine3.19
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        volumes:
            - ./postgres:/var/lib/postgresql/data:z
        ports:
            - ${DB_EXPOSED}:5432
