# Generated by Django 5.0.1 on 2024-02-06 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_id', models.CharField(max_length=30)),
                ('price_variation_24h', models.DecimalField(decimal_places=5, max_digits=10)),
                ('price_variation_7d', models.DecimalField(decimal_places=5, max_digits=10)),
                ('last_price_value', models.DecimalField(decimal_places=10, max_digits=22)),
                ('last_price_currency', models.CharField(max_length=15)),
                ('max_bid_value', models.DecimalField(decimal_places=10, max_digits=22)),
                ('max_bid_currency', models.CharField(max_length=15)),
                ('min_ask_value', models.DecimalField(decimal_places=10, max_digits=22)),
                ('min_ask_currency', models.CharField(max_length=15)),
                ('volume_value', models.DecimalField(decimal_places=10, max_digits=22)),
                ('volume_currency', models.CharField(max_length=15)),
                ('fetch_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Spread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_id', models.CharField(max_length=30)),
                ('value', models.DecimalField(decimal_places=10, max_digits=22)),
                ('currency', models.CharField(max_length=15)),
                ('fetch_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
