# Generated by Django 5.0.1 on 2024-02-08 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_market'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_id', models.CharField(max_length=30)),
                ('current_spread_value', models.DecimalField(decimal_places=10, max_digits=22)),
                ('current_spread_currency', models.CharField(max_length=15)),
                ('stored_spread_value', models.DecimalField(decimal_places=10, max_digits=22)),
                ('stored_spread_currency', models.CharField(max_length=15)),
                ('stored_spread_date', models.DateTimeField()),
                ('result', models.CharField(max_length=50)),
                ('is_greater', models.BooleanField()),
                ('is_smaller', models.BooleanField()),
                ('are_equals', models.BooleanField()),
                ('fetch_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
